### ISSUE TITLE
Unable to use flycheck-dmd-dub with sub-packages

### ISSUE THREAD

**Issue by SerialVelocity** [atilaneves/flycheck-dmd-dub#7]
Hey, using sub-packages in dub breaks flycheck-dmd-dub. It is running dub describe in the sub-package folder instead of the package folder.

```
Debugger entered--Lisp error: (wrong-type-argument integerp nil)
  fldd--get-dub-package-dirs-output("Error executing command describe: Root package SUB_PACKAGE_1 contains reference to invalid package PACKAGE:SUB_PACKAGE_2\n\n")
  fldd--get-dub-package-dirs()
  ac-dcd-find-imports-dub()
  ac-dcd-add-imports()
  call-interactively(ac-dcd-add-imports record nil)
  command-execute(ac-dcd-add-imports record)
  execute-extended-command(nil "ac-dcd-add-imports")
  call-interactively(execute-extended-command nil nil)
```

**Comment by atilaneves** [comment]
git sub-packages? Can you add a reproducible scenario please?

**Comment by SerialVelocity** [comment]
Sorry, not git sub-packages, dub sub-packages.

**Comment by atilaneves** [comment]
The please add offending dub.json files and directory structure.

**Comment by SerialVelocity** [comment]
I think this should fail if you try with the following:

PACKAGE/dub.json:
```json
{
  "name": "PACAKGE",
  "targetType": "none",
  "subPackages": [
    "SUB-PACKAGE-1",
    "SUB-PACKAGE-2"
  ]
}
```
PACKAGE/SUB-PACKAGE-1/dub.json
```json
{
  "name": "SUB-PACKAGE-1",
  "targetType": "library",
  "depdendencies": [
    "PACKAGE:SUB-PACKAGE-2"
  ]
}
```
PACKAGE/SUB-PACKAGE-2/dub.json
```json
{
  "name": "SUB-PACKAGE-2",
  "targetType": "library"
}
```

**Comment by SerialVelocity** [comment]
Huh, it seems that cmake-ide do this in a weird way. It's weird because you have some projects which store their dependencies as submodules. If you did a parent directory search for ```dub.json``` or ```package.json``` then you would get the wrong one.

Also, does this break ac-dcd?

**Comment by atilaneves** [comment]
`ac-dcd` still works for me. `cmake-ide` does it the way it does for the same reason, CMake projects can (and usually do) have nested `CMakeLists.txt` files. So this just keeps searching upwards until it can't find another dub.json/package.json file.
